# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_ShareEditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShareEditor(object):
    def setupUi(self, ShareEditor):
        ShareEditor.setObjectName("ShareEditor")
        ShareEditor.resize(922, 806)
        self.centralwidget = QtWidgets.QWidget(ShareEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.schedule_name = QtWidgets.QLineEdit(self.centralwidget)
        self.schedule_name.setText("")
        self.schedule_name.setObjectName("schedule_name")
        self.horizontalLayout_5.addWidget(self.schedule_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.share_link = QtWidgets.QLineEdit(self.centralwidget)
        self.share_link.setObjectName("share_link")
        self.horizontalLayout_3.addWidget(self.share_link)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.schedule_notes = QtWidgets.QLineEdit(self.centralwidget)
        self.schedule_notes.setObjectName("schedule_notes")
        self.horizontalLayout_7.addWidget(self.schedule_notes)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Enable_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.Enable_cb.setObjectName("Enable_cb")
        self.horizontalLayout_2.addWidget(self.Enable_cb)
        self.randomlink_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.randomlink_cb.setObjectName("randomlink_cb")
        self.horizontalLayout_2.addWidget(self.randomlink_cb)
        self.randomtime_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.randomtime_cb.setObjectName("randomtime_cb")
        self.horizontalLayout_2.addWidget(self.randomtime_cb)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.saveall_btn = QtWidgets.QPushButton(self.centralwidget)
        self.saveall_btn.setObjectName("saveall_btn")
        self.verticalLayout_9.addWidget(self.saveall_btn)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.PastlinkList = QtWidgets.QTableWidget(self.centralwidget)
        self.PastlinkList.setObjectName("PastlinkList")
        self.PastlinkList.setColumnCount(0)
        self.PastlinkList.setRowCount(0)
        self.verticalLayout_6.addWidget(self.PastlinkList)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.Addlink_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Addlink_btn.setObjectName("Addlink_btn")
        self.horizontalLayout_10.addWidget(self.Addlink_btn)
        self.Removelink_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Removelink_btn.setObjectName("Removelink_btn")
        self.horizontalLayout_10.addWidget(self.Removelink_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Timelist = QtWidgets.QTableWidget(self.centralwidget)
        self.Timelist.setObjectName("Timelist")
        self.Timelist.setColumnCount(0)
        self.Timelist.setRowCount(0)
        self.verticalLayout_7.addWidget(self.Timelist)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.Addtime_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Addtime_btn.setObjectName("Addtime_btn")
        self.horizontalLayout_14.addWidget(self.Addtime_btn)
        self.Removetime_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Removetime_btn.setObjectName("Removetime_btn")
        self.horizontalLayout_14.addWidget(self.Removetime_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Sharelist = QtWidgets.QTableWidget(self.centralwidget)
        self.Sharelist.setObjectName("Sharelist")
        self.Sharelist.setColumnCount(0)
        self.Sharelist.setRowCount(0)
        self.verticalLayout_2.addWidget(self.Sharelist)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.RemoveAC_btn = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveAC_btn.setObjectName("RemoveAC_btn")
        self.horizontalLayout_9.addWidget(self.RemoveAC_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CommentList = QtWidgets.QTableWidget(self.centralwidget)
        self.CommentList.setObjectName("CommentList")
        self.CommentList.setColumnCount(0)
        self.CommentList.setRowCount(0)
        self.verticalLayout.addWidget(self.CommentList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.AddComment = QtWidgets.QPushButton(self.centralwidget)
        self.AddComment.setObjectName("AddComment")
        self.horizontalLayout.addWidget(self.AddComment)
        self.RemoveComment = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveComment.setObjectName("RemoveComment")
        self.horizontalLayout.addWidget(self.RemoveComment)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.ShareUsername_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ShareUsername_comboBox.setObjectName("ShareUsername_comboBox")
        self.horizontalLayout_4.addWidget(self.ShareUsername_comboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_6.addWidget(self.timeEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Group_table = QtWidgets.QTableWidget(self.centralwidget)
        self.Group_table.setAcceptDrops(True)
        self.Group_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Group_table.setDragEnabled(True)
        self.Group_table.setDragDropOverwriteMode(False)
        self.Group_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.Group_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.Group_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Group_table.setObjectName("Group_table")
        self.Group_table.setColumnCount(0)
        self.Group_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.Group_table)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SelectedGroup_table = QtWidgets.QTableWidget(self.centralwidget)
        self.SelectedGroup_table.setAcceptDrops(True)
        self.SelectedGroup_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.SelectedGroup_table.setDragEnabled(True)
        self.SelectedGroup_table.setDragDropOverwriteMode(False)
        self.SelectedGroup_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.SelectedGroup_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.SelectedGroup_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SelectedGroup_table.setObjectName("SelectedGroup_table")
        self.SelectedGroup_table.setColumnCount(0)
        self.SelectedGroup_table.setRowCount(0)
        self.verticalLayout_4.addWidget(self.SelectedGroup_table)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.AddAC_btn = QtWidgets.QPushButton(self.centralwidget)
        self.AddAC_btn.setObjectName("AddAC_btn")
        self.verticalLayout_10.addWidget(self.AddAC_btn)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        ShareEditor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ShareEditor)
        self.statusbar.setObjectName("statusbar")
        ShareEditor.setStatusBar(self.statusbar)

        self.retranslateUi(ShareEditor)
        QtCore.QMetaObject.connectSlotsByName(ShareEditor)

    def retranslateUi(self, ShareEditor):
        _translate = QtCore.QCoreApplication.translate
        ShareEditor.setWindowTitle(_translate("ShareEditor", "Share Editor"))
        self.label_4.setText(_translate("ShareEditor", "Schedule Name:"))
        self.label_5.setText(_translate("ShareEditor", "Share Link:"))
        self.label_7.setText(_translate("ShareEditor", "Schedule Notes:"))
        self.Enable_cb.setText(_translate("ShareEditor", "Enable"))
        self.randomlink_cb.setText(_translate("ShareEditor", "Random Past Links"))
        self.randomtime_cb.setText(_translate("ShareEditor", "Random Selected Time"))
        self.saveall_btn.setText(_translate("ShareEditor", "Save All and Return"))
        self.label_12.setText(_translate("ShareEditor", "Schedule_id: None"))
        self.label_8.setText(_translate("ShareEditor", "Links"))
        self.Addlink_btn.setText(_translate("ShareEditor", "Add"))
        self.Removelink_btn.setText(_translate("ShareEditor", "Remove"))
        self.label_11.setText(_translate("ShareEditor", "Time List:"))
        self.Addtime_btn.setText(_translate("ShareEditor", "Add"))
        self.Removetime_btn.setText(_translate("ShareEditor", "Remove"))
        self.label_2.setText(_translate("ShareEditor", "Account - Group List:"))
        self.RemoveAC_btn.setText(_translate("ShareEditor", "Remove"))
        self.label.setText(_translate("ShareEditor", "Comments List:"))
        self.AddComment.setText(_translate("ShareEditor", "Add"))
        self.RemoveComment.setText(_translate("ShareEditor", "Remove"))
        self.label_6.setText(_translate("ShareEditor", "Share Username:"))
        self.label_3.setText(_translate("ShareEditor", "Time"))
        self.timeEdit.setDisplayFormat(_translate("ShareEditor", "h:mm"))
        self.label_9.setText(_translate("ShareEditor", "Group Table"))
        self.label_10.setText(_translate("ShareEditor", "Selected Group Table"))
        self.AddAC_btn.setText(_translate("ShareEditor", "Add To Account - Group List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShareEditor = QtWidgets.QMainWindow()
    ui = Ui_ShareEditor()
    ui.setupUi(ShareEditor)
    ShareEditor.show()
    sys.exit(app.exec_())

