from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Login)
        self.buttonBox.setGeometry(QtCore.QRect(30, 200, 231, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.Username = QtWidgets.QLineEdit(Login)
        self.Username.setGeometry(QtCore.QRect(170, 60, 201, 41))
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(Login)
        self.Password.setGeometry(QtCore.QRect(170, 120, 201, 41))
        self.Password.setObjectName("Password")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label = QtWidgets.QLabel(Login)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(40, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Signup_btn = QtWidgets.QPushButton(Login)
        self.Signup_btn.setGeometry(QtCore.QRect(200, 200, 91, 31))
        self.Signup_btn.setObjectName("Signup_btn")
        self.Login_btn = QtWidgets.QPushButton(Login)
        self.Login_btn.setGeometry(QtCore.QRect(90, 200, 91, 31))
        self.Login_btn.setObjectName("Login_btn")
        self.retranslateUi(Login)
        self.buttonBox.accepted.connect(Login.accept)
        self.buttonBox.rejected.connect(Login.reject)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Username"))
        self.label_2.setText(_translate("Login", "Password"))
        self.Signup_btn.setText(_translate("Login", "Signup"))
        self.Login_btn.setText(_translate("Login", "Login"))