from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(405, 317)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 180, 231, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.Signup_btn = QtWidgets.QPushButton(Dialog)
        self.Signup_btn.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.Signup_btn.setObjectName("Signup_btn")
        self.Username = QtWidgets.QLineEdit(Dialog)
        self.Username.setGeometry(QtCore.QRect(160, 40, 201, 41))
        self.Username.setObjectName("Username")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(30, 50, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Password = QtWidgets.QLineEdit(Dialog)
        self.Password.setGeometry(QtCore.QRect(160, 100, 201, 41))
        self.Password.setObjectName("Password")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_2 = QtWidgets.QLineEdit(Dialog)
        self.Password_2.setGeometry(QtCore.QRect(160, 160, 201, 41))
        self.Password_2.setObjectName("Password_2")
        self.Password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Password_3 = QtWidgets.QLineEdit(Dialog)
        self.Password_3.setGeometry(QtCore.QRect(290, 230, 81, 41))
        self.Password_3.setObjectName("Password_3")
        self.Password_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(150, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Signup_btn.setText(_translate("Dialog", "Signup"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label_3.setText(_translate("Dialog", "Confirm_Password"))
        self.label_4.setText(_translate("Dialog", "Code (Ask Jack)"))