# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(709, 765)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.Username_comboBox = QtWidgets.QComboBox(self.tab)
        self.Username_comboBox.setObjectName("Username_comboBox")
        self.horizontalLayout_2.addWidget(self.Username_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RetrieveCookies_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.RetrieveCookies_rbtn.setChecked(True)
        self.RetrieveCookies_rbtn.setObjectName("RetrieveCookies_rbtn")
        self.horizontalLayout_5.addWidget(self.RetrieveCookies_rbtn)
        self.LoadCookies_rbtn = QtWidgets.QRadioButton(self.groupBox)
        self.LoadCookies_rbtn.setObjectName("LoadCookies_rbtn")
        self.horizontalLayout_5.addWidget(self.LoadCookies_rbtn)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.FBtoolkit_cb = QtWidgets.QCheckBox(self.tab)
        self.FBtoolkit_cb.setObjectName("FBtoolkit_cb")
        self.horizontalLayout.addWidget(self.FBtoolkit_cb)
        self.UpdateGL_cb = QtWidgets.QCheckBox(self.tab)
        self.UpdateGL_cb.setObjectName("UpdateGL_cb")
        self.horizontalLayout.addWidget(self.UpdateGL_cb)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AutoShutdown_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.AutoShutdown_rbtn.setChecked(True)
        self.AutoShutdown_rbtn.setObjectName("AutoShutdown_rbtn")
        self.horizontalLayout_4.addWidget(self.AutoShutdown_rbtn)
        self.NoAction_rbtn = QtWidgets.QRadioButton(self.groupBox_2)
        self.NoAction_rbtn.setObjectName("NoAction_rbtn")
        self.horizontalLayout_4.addWidget(self.NoAction_rbtn)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.submit_btn_2 = QtWidgets.QPushButton(self.tab)
        self.submit_btn_2.setObjectName("submit_btn_2")
        self.verticalLayout_3.addWidget(self.submit_btn_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        TabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.ShareUsername_comboBox = QtWidgets.QComboBox(self.tab_4)
        self.ShareUsername_comboBox.setObjectName("ShareUsername_comboBox")
        self.horizontalLayout_8.addWidget(self.ShareUsername_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.Link_line = QtWidgets.QLineEdit(self.tab_4)
        self.Link_line.setObjectName("Link_line")
        self.horizontalLayout_13.addWidget(self.Link_line)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.Comment_line = QtWidgets.QLineEdit(self.tab_4)
        self.Comment_line.setObjectName("Comment_line")
        self.horizontalLayout_12.addWidget(self.Comment_line)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Group_table = QtWidgets.QTableWidget(self.tab_4)
        self.Group_table.setAcceptDrops(True)
        self.Group_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Group_table.setDragEnabled(True)
        self.Group_table.setDragDropOverwriteMode(False)
        self.Group_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.Group_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.Group_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Group_table.setObjectName("Group_table")
        self.Group_table.setColumnCount(0)
        self.Group_table.setRowCount(0)
        self.verticalLayout_5.addWidget(self.Group_table)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.SelectedGroup_table = QtWidgets.QTableWidget(self.tab_4)
        self.SelectedGroup_table.setAcceptDrops(True)
        self.SelectedGroup_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.SelectedGroup_table.setDragEnabled(True)
        self.SelectedGroup_table.setDragDropOverwriteMode(False)
        self.SelectedGroup_table.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.SelectedGroup_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.SelectedGroup_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SelectedGroup_table.setObjectName("SelectedGroup_table")
        self.SelectedGroup_table.setColumnCount(0)
        self.SelectedGroup_table.setRowCount(0)
        self.verticalLayout_8.addWidget(self.SelectedGroup_table)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.submit_btn = QtWidgets.QPushButton(self.tab_4)
        self.submit_btn.setObjectName("submit_btn")
        self.horizontalLayout_9.addWidget(self.submit_btn)
        self.timeline_cb = QtWidgets.QCheckBox(self.tab_4)
        self.timeline_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.timeline_cb.setObjectName("timeline_cb")
        self.horizontalLayout_9.addWidget(self.timeline_cb)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        TabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.scheduler_table = QtWidgets.QTableWidget(self.tab_2)
        self.scheduler_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.scheduler_table.setObjectName("scheduler_table")
        self.scheduler_table.setColumnCount(0)
        self.scheduler_table.setRowCount(0)
        self.gridLayout.addWidget(self.scheduler_table, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_btn = QtWidgets.QPushButton(self.tab_2)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.remove_btn = QtWidgets.QPushButton(self.tab_2)
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout.addWidget(self.remove_btn)
        self.edit_btn = QtWidgets.QPushButton(self.tab_2)
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout.addWidget(self.edit_btn)
        self.refresh_btn = QtWidgets.QPushButton(self.tab_2)
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout.addWidget(self.refresh_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        TabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.schedule_table = QtWidgets.QTableWidget(self.tab_5)
        self.schedule_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.schedule_table.setObjectName("schedule_table")
        self.schedule_table.setColumnCount(0)
        self.schedule_table.setRowCount(0)
        self.verticalLayout_6.addWidget(self.schedule_table)
        self.run_schedule_btn = QtWidgets.QPushButton(self.tab_5)
        self.run_schedule_btn.setObjectName("run_schedule_btn")
        self.verticalLayout_6.addWidget(self.run_schedule_btn)
        self.refresh_schedule_btn = QtWidgets.QPushButton(self.tab_5)
        self.refresh_schedule_btn.setObjectName("refresh_schedule_btn")
        self.verticalLayout_6.addWidget(self.refresh_schedule_btn)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        TabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_3.sizePolicy().hasHeightForWidth())
        self.tab_3.setSizePolicy(sizePolicy)
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.refresh_btn_2 = QtWidgets.QPushButton(self.tab_3)
        self.refresh_btn_2.setObjectName("refresh_btn_2")
        self.gridLayout_2.addWidget(self.refresh_btn_2, 1, 0, 1, 1)
        self.group_type_btn = QtWidgets.QPushButton(self.tab_3)
        self.group_type_btn.setObjectName("group_type_btn")
        self.gridLayout_2.addWidget(self.group_type_btn, 2, 0, 1, 1)
        TabWidget.addTab(self.tab_3, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Facebook Software - FANS Marketing Planning Limited"))
        self.label_6.setText(_translate("TabWidget", "Maintenance Actions"))
        self.label.setText(_translate("TabWidget", "Username:"))
        self.groupBox.setTitle(_translate("TabWidget", "Login Method:"))
        self.RetrieveCookies_rbtn.setText(_translate("TabWidget", "Retrieve Cookies"))
        self.LoadCookies_rbtn.setText(_translate("TabWidget", "Load Cookies"))
        self.label_3.setText(_translate("TabWidget", "Other Functions:"))
        self.FBtoolkit_cb.setText(_translate("TabWidget", "FB toolkit"))
        self.UpdateGL_cb.setText(_translate("TabWidget", "Update Group List"))
        self.groupBox_2.setTitle(_translate("TabWidget", "When Action Complete:"))
        self.AutoShutdown_rbtn.setText(_translate("TabWidget", "Auto Shutdown"))
        self.NoAction_rbtn.setText(_translate("TabWidget", "No Action"))
        self.submit_btn_2.setText(_translate("TabWidget", "Perform Action(s)!"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Maintenance Actions"))
        self.label_7.setText(_translate("TabWidget", "Share Action"))
        self.label_5.setText(_translate("TabWidget", "Share Username:"))
        self.label_11.setText(_translate("TabWidget", "Share Link:"))
        self.label_8.setText(_translate("TabWidget", "Share Comment:"))
        self.label_9.setText(_translate("TabWidget", "Group Table"))
        self.label_10.setText(_translate("TabWidget", "Selected Group Table"))
        self.submit_btn.setText(_translate("TabWidget", "FB Share Now"))
        self.timeline_cb.setText(_translate("TabWidget", "Also Share to User Timeline"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "Share(Now)"))
        self.add_btn.setText(_translate("TabWidget", "Add"))
        self.remove_btn.setText(_translate("TabWidget", "Remove"))
        self.edit_btn.setText(_translate("TabWidget", "Edit"))
        self.refresh_btn.setText(_translate("TabWidget", "Refresh"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "Share Scheduler"))
        self.run_schedule_btn.setText(_translate("TabWidget", "Run Schedules"))
        self.refresh_schedule_btn.setText(_translate("TabWidget", "Refresh Schedules"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_5), _translate("TabWidget", "Upcoming Schedules"))
        self.refresh_btn_2.setText(_translate("TabWidget", "Refresh"))
        self.group_type_btn.setText(_translate("TabWidget", "Change Group Type"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "Account Infos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

